### ISSUE TITLE
android takes encoded string as display name

### ISSUE THREAD

**Issue by Sebastian-Lemling** [SURFnet/tiqr-client-android#156] opened 2022-08-03 12:20 UTC
We had a problem with IOS that if the display name contained spaces, the authentication was unsuccessful because spaces were contained in the url. This was our mistake as this is inherently correct behavior as spaces should not be included in a url.

After we encoded the displayname we noticed the following:

- On IOS everything works as expected. Authentication successful, the string is encoded and the display name is displayed in the APP with spaces. `My Service Name`
- With Android, however, the encoded string is displayed as the display name in the app. `My%20Service%20Name`

Strangely, Android was able to process the spaces and display them correctly without encoding. However, the authentication with IOS then failed.

https://github.com/privacyidea/privacyidea/issues/3121

**Comment by pmeulen** [comment] 2022-08-23 12:02
Thanks for your report. I can confirm that the iOS and Tiqr app behave differently in their handling of the server identification part of the authentication URL. The iOS behaviour seems correct. As far as I can tell this parameter was intended to display the identifier (domain name) of the server and not the display name. I'm not happy with how this feature is implemented now because it's value is not authenticated (e.g. it is not part of the OCRA SessionInfo) so a MITM could change this value to anything to mislead a user and the authentication would still work.

I see why you would want to show a friendly name of the server here to the user and we're thinkig of a better way of implementing this. We're working on a new tiqr release and have introduced a new URL format, which does not support a server display name for now but is flexible enough that it could be added.

Note that everything Tiqr related is moving to https://github.com/Tiqr/ 
I've created an issue there: https://github.com/Tiqr/tiqr-app-core-android/issues/47

**Closed as completed** 2022-08-23 13:14 UTC
